### ISSUE TITLE
Integrate Mixcloud

### ISSUE THREAD

**Issue by LoveIsGrief** [LoveIsGrief/videojs-externals#17]
[API doc](https://www.mixcloud.com/developers/widget/)

[Example](https://codepen.io/anon/pen/ZKpKXM?editors=1010#0)

# TODO

- [x] play
- [x] pause
- [x] seek
- [x] change source dynamically
- [ ] poster
- [x] pass all tests
- [ ] check tests of other externals

**Comment by LoveIsGrief** [comment]
... can't continue. Can't listen to Mixcloud PlayerWidget events. The [codepen](https://codepen.io/anon/pen/gGoBPw?editors=1010#0) shows an example ...
